package component-test:wit-protocol;

world flags-test {
  flags colors {
    red,
    green,
    blue
  }

  import import-add-green: func(color: colors) -> colors;
  export export-add-green-and-blue: func(color: colors) -> colors;

  import import-push-green: func(colors: list<colors>) -> list<colors>;
  export export-push-green-and-blue: func(colors: list<colors>) -> list<colors>;

  flags many-flags {
    flag00,
    flag01,
    flag02,
    flag03,
    flag04,
    flag05,
    flag06,
    flag07,
    flag08,
    flag09,
    flag10,
    flag11,
    flag12,
    flag13,
    flag14,
    flag15,
    flag16,
    flag17,
    flag18,
    flag19,
    flag20,
    flag21,
    flag22,
    flag23,
    flag24,
    flag25,
    flag26,
    flag27,
    flag28,
    flag29,
    flag30,
    flag31,
    flag32,
    flag33,
    flag34,
    flag35,
    flag36,
    flag37,
    flag38,
    flag39,
  }

  import import-add-first: func(values: many-flags) -> many-flags;
  export export-add-first-and-last: func(values: many-flags) -> many-flags;

  import import-push-first: func(values: list<many-flags>) -> list<many-flags>;
  export export-push-first-and-last: func(values: list<many-flags>) -> list<many-flags>;
}
