package component-test:wasi-protocol;

world io-redirect {
  export readln-from-stdin: func() -> option<string>;
  export writeln-to-stdout: func(line: string);
  export writeln-to-stderr: func(line: string);
}
