package component-test:wit-protocol;

interface companies {
  resource company {
    constructor(name: string, max-salary: u32);
    get-name: func() -> string;
    get-max-salary: func() -> u32;
  }
}


world resources {
  import companies;

  export create-company: func(name: string) -> string;
}
