package component-test:wit-protocol;

interface companies {
  resource company-res {
    constructor(name: string, max-salary: u32);
    get-name: func() -> string;
    set-name: func(name: string);
    get-max-salary: func() -> u32;
  }
}

interface host-fns {
  // use employees.{employee};
  use companies.{company-res};

  // Cannot use guest resources in host imported functions, see
  // https://bytecodealliance.zulipchat.com/#narrow/stream/327223-wit-bindgen/topic/.E2.9C.94.20Guest.20resource.20gets.20duplicated
  // employee-roundtrip: func(employee: employee) -> employee;
  company-roundtrip: func(company: company-res) -> company-res;
}

interface employees {
  resource employee-res {
    constructor(name: string, min-salary: u32);
    get-name: func() -> string;
    set-name: func(name: string);
    get-min-salary: func() -> u32;
  }
}

interface guest-fns {
  use employees.{employee-res};
  use companies.{company-res};

  employee-roundtrip: func(employee: employee-res) -> employee-res;
  company-roundtrip: func(company: company-res) -> company-res;

  method-find-job: func(employee: employee-res, companies: list<company-res>) -> option<company-res>;
}

world resources {
  import companies;
  import host-fns;
  
  export employees;
  export guest-fns;

  export simple: func();
  import log: func(message: string);
}
