package component-test:wit-protocol

world records {
  // Record structs
  // record item {
  //   a: u32,
  //   b: u64,
  // }

  export run: func(arg: u32)
  // export run: func(args: list<u32>) 
  // import send-item: func(item: item)
}
