package component-test:wit-protocol

world records {
  // Record structs
  record player {
    name: string,
    inventory: list<string>,
    counts: list<u32>,
  }

  import create-player: func(name: string, inventory: list<string>, counts: list<u32>) -> player
  export get-inventory: func() -> list<string>
  export get-counts: func() -> list<u32>
}
