package wasm-bridge:protocol

world test-world {
  export add-hello: func(text: string) -> string

  import add-b: func(text: string) -> string
  export add-abc: func(text: string) -> string

  import add-numbers-import: func(a: s32, b: s32) -> s32
  export add-numbers: func(a: s32, b: s32) -> s32

  import increment: func()
  export increment-twice: func()

  import add-all: func(a: s32, b: s64, c: u32, d: u64, e: float32, f: float64, g: string) -> float64
  export add-all-and-one: func(a: s32, b: s64, c: u32, d: u64, e: float32, f: float64, g: string) -> float64

  export add-sub-one: func(num: s32) -> tuple<s32, s32>
}
