package wasm-bridge:protocol

world test-world {
  import add-b: func(text: string) -> string

  export add-hello: func(text: string) -> string
  export add-abc: func(text: string) -> string

  export add-numbers: func(a: s32, b: s32) -> s32
}
