package component-test:wit-protocol;

world simple {
  export push-s32s: func(nums: list<s32>, a: s32, b: s32) -> list<s32>;
  export push-u32s: func(nums: list<u32>, a: u32, b: u32) -> list<u32>;
  export voider: func();
  export pairs12: func() -> (a: s32, b: s32);

  record vector {
    x: s32,
    y: s32,
    z: s32,
  }
  export get-vector123: func() -> vector;

  export get-many-vectors: func(amount: u32) -> list<vector>;

  record player {
    position: vector,
    velocity: vector,
    looking-at: vector,
    health: u32,
    max-health: u32,
  }

  export heal-players: func(players: list<player>, healing: u32) -> list<player>;
  export move-players: func(players: list<player>, scale: s32) -> list<player>;

  export player-look-at: func(player: player, look: vector) -> player;
}
